services:
  mongo:
    image: mongo:8
    container_name: blog-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - blog-net

  backend:
    build: ./backend
    container_name: blog-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    networks:
      - blog-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: blog-frontend
    restart: unless-stopped
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "5175:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - blog-net

volumes:
  mongo_data:
  frontend_node_modules:

networks:
  blog-net:
    driver: bridge
